[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Pxcw00xn")]
[assembly: System.Reflection.AssemblyCompany("Banrisul")]
[assembly: System.Reflection.AssemblyProduct("Pxcw00xn")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Banrisul 2026")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("afbe4c90-25ea-4aba-95e0-be2080d04b9e")]
