[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Pxcwidxn")]
[assembly: System.Reflection.AssemblyCompany("Banrisul")]
[assembly: System.Reflection.AssemblyProduct("Pxcwidxn")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Banrisul 2026")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("7d207419-8693-4975-ae69-84e5e56be96f")]
